package pe.egcc.angelesapp.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Gustavo Coronel Castillo
 * @email gcoronelc@gmail.com
 * @blog gcoronelc.blogspot.com
 * @page www.desarrollasoftware.com
 */
public class MainView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public MainView() {
    initComponents();
    this.setExtendedState(MAXIMIZED_BOTH);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    btnFactorial = new javax.swing.JButton();
    btnMcdMcm = new javax.swing.JButton();
    btnFibonacci = new javax.swing.JButton();
    btnPrimo = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    btnSalir = new javax.swing.JButton();
    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuArchivoSalir = new javax.swing.JMenuItem();
    menuMate = new javax.swing.JMenu();
    menuMateFactorial = new javax.swing.JMenuItem();
    menuMateMcdMcm = new javax.swing.JMenuItem();
    menuMateFibonacci = new javax.swing.JMenuItem();
    menuMatePrimo = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("MATE EXPERT");

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    btnFactorial.setText("Factorial");
    btnFactorial.setToolTipText("");
    btnFactorial.setFocusable(false);
    btnFactorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnFactorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnFactorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFactorialActionPerformed(evt);
      }
    });
    jToolBar1.add(btnFactorial);

    btnMcdMcm.setText("MCD y MCM");
    btnMcdMcm.setFocusable(false);
    btnMcdMcm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnMcdMcm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btnMcdMcm);

    btnFibonacci.setText("Fibonacci");
    btnFibonacci.setFocusable(false);
    btnFibonacci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnFibonacci.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btnFibonacci);

    btnPrimo.setText("Primo");
    btnPrimo.setFocusable(false);
    btnPrimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnPrimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnPrimo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPrimoActionPerformed(evt);
      }
    });
    jToolBar1.add(btnPrimo);
    jToolBar1.add(jSeparator1);

    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/angelesapp/img/exit.png"))); // NOI18N
    btnSalir.setToolTipText("Salir del sistema.");
    btnSalir.setFocusable(false);
    btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });
    jToolBar1.add(btnSalir);

    menuArchivo.setText("Archivo");

    menuArchivoSalir.setText("Salir");
    menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuArchivoSalirActionPerformed(evt);
      }
    });
    menuArchivo.add(menuArchivoSalir);

    menuBar.add(menuArchivo);

    menuMate.setText("Matematica");

    menuMateFactorial.setText("Factorial");
    menuMateFactorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuMateFactorialActionPerformed(evt);
      }
    });
    menuMate.add(menuMateFactorial);

    menuMateMcdMcm.setText("MCD y MCM");
    menuMate.add(menuMateMcdMcm);

    menuMateFibonacci.setText("Fibonacci");
    menuMate.add(menuMateFibonacci);

    menuMatePrimo.setText("Primo");
    menuMatePrimo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuMatePrimoActionPerformed(evt);
      }
    });
    menuMate.add(menuMatePrimo);

    menuBar.add(menuMate);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnSalirActionPerformed

  private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
    loadInternalform(FactorialView.class);
  }//GEN-LAST:event_btnFactorialActionPerformed

  private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
    loadInternalform(PrimoView.class);
  }//GEN-LAST:event_btnPrimoActionPerformed

  private void menuMateFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateFactorialActionPerformed
    loadInternalform(FactorialView.class);
  }//GEN-LAST:event_menuMateFactorialActionPerformed

  private void menuMatePrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatePrimoActionPerformed
    loadInternalform(PrimoView.class);
  }//GEN-LAST:event_menuMatePrimoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnFactorial;
  private javax.swing.JButton btnFibonacci;
  private javax.swing.JButton btnMcdMcm;
  private javax.swing.JButton btnPrimo;
  private javax.swing.JButton btnSalir;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenuItem menuArchivoSalir;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuMate;
  private javax.swing.JMenuItem menuMateFactorial;
  private javax.swing.JMenuItem menuMateFibonacci;
  private javax.swing.JMenuItem menuMateMcdMcm;
  private javax.swing.JMenuItem menuMatePrimo;
  // End of variables declaration//GEN-END:variables

  private void loadInternalform(Class<?> aClass) {
    try {
      // Variable de control
      JInternalFrame view = null;
      // Buscando una instancia
      for (JInternalFrame instancia : desktopPane.getAllFrames()) {
        if (aClass.isInstance(instancia)) {
          view = instancia;
          break;
        }
      }
      // Creando la instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName())
                .newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activar el formulario
      view.setSelected(true);
    } catch (Exception e) {
    }
  }

}
